apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: mongodb
  project: {{ .Values.spec.project }}
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.1.4
    helm:
      releaseName: mongodb
      values: |
        auth:
          enabled: false
  syncPolicy:
    {{ toYaml .Values.spec.defaultSyncOptions | nindent 8 }}
    {{ toYaml .Values.spec.defaultAutomated | nindent 8 }}
    {{ toYaml .Values.spec.defaultRetry | nindent 8 }}
