{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "iptoolkits.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongo }}
{{- end }}