# Default values for iptoolkits.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: naviat/iptoolkits
  pullPolicy: IfNotPresent
  tag: "$IMAGE_TAG"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: iptoolkits.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  enabled: true
  name: db-secrets
  # MONGO_URI: "mongodb://mongodb-standalone.mongodb:27017/iptoolkits"
  mongo: bW9uZ29kYjovL21vbmdvZGItc3RhbmRhbG9uZS5tb25nb2RiOjI3MDE3L2lwdG9vbGtpdHM=

config:
  name: ip-configs
  vars:
    KUBERNETES: "true"
    PORT: "3000"
    #MONGO_URI: "mongodb://mongodb:27017/iptoolkits?authSource=admin"

reloader:
  enabled: true