---
name: Helm Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/**
      - platform-apps/**
    types:
      - opened
      - reopened
      - synchronize

jobs:
  helm-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git unzip

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@main
        with:
          files: |
            apps/**
            platform-apps/**

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Helm lint check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              chart=$(echo $file | cut -d/ -f 1-2)
              values_dir="$chart/values"
              # Check and lint values in the 'values' directories
              if [[ -d "$values_dir" ]]; then
                  for value_file in $(find "$values_dir" -type f); do
                      echo "helm lint $chart -f $value_file"
                      helm lint "$chart" -f "$value_file"
                  done
              fi
              # Fallback to lint the chart without specific value
              # files if none of the directories exist
              if [[ ! -d "$values_dir" ]]; then
                  helm lint "$chart"
              fi
          done
        shell: bash
