---
name: JSON Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/**/values/**
    types:
      - opened
      - reopened
      - synchronize

jobs:
  json-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@main
        with:
          files: |
            apps/**/values/**

      - name: JSON lint
        uses: dungpham91/lint-json-inside-yaml@main
        with:
          folder_or_file: ${{ steps.changed-files.outputs.all_changed_files }}
