name: JSON Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/**/values/**
    types:
      - opened
      - reopened
      - synchronize

jobs:
  json-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@8238a4103220c636f2dad328ead8a7c8dbe316a3 # v39.2.0
        with:
          files: |
            apps/**/values/**

      - name: JSON lint
        uses: dungpham91/lint-json-inside-yaml@ee76a68fafcf4b959e711e24d11d9c4f33137e80 # v0.0.2
        with:
          folder_or_file: ${{ steps.changed-files.outputs.all_changed_files }}
