name: Yaml Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - environments/**
    types:
      - opened
      - reopened
      - synchronize

jobs:
  yaml-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git
          sudo apt install -y yamllint

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@8238a4103220c636f2dad328ead8a7c8dbe316a3 # v39.2.0
        with:
          files: |
            .github/**
            environments/**

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ steps.changed-files.outputs.all_changed_files }}
          config_data: |
            extends: default
            rules:
              braces:
                max-spaces-inside: 1
              line-length:
                max: 160
                allow-non-breakable-words: true
                allow-non-breakable-inline-mappings: false
